### ISSUE TITLE
common-linux-command

### ISSUE THREAD

**Issue by swolicetax** [S2U2MLancer/Cookbook#1]
[common linux command](http://www.cnblogs.com/bananaaa/p/7774467.html)

**Comment by xiayy860612** [comment]
我觉得还有shell里面一些常用的语法,
比如 if, for, 表达式, i/o等等

**Comment by swolicetax** [comment]
@xiayy860612 这个要另列一章，专门讨论bash shell的特性。不属于命令的范围。
